
name: Deploy prod site on push

on: 
  push:
    branches: 
      - main
      
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build
    
    - name: Sync Files
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.FTP_SERVER }}
        ftp_username: ${{ secrets.FTP_USER }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "dist"
        dist_target_dir: "/"
        delete: "true"
        exclude: "'^logs/' '^README.md'"
